defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:7.10

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: yarn install
      - run: yarn run build
      - persist_to_workspace:
          root: build

  deploy_master:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo/build
      # change to deployment command later
      - run: ls -a

workflows:
  version: 2

  build_and_deploy_master:
    jobs:
      - build
      - deploy_master:
          requires:
            - build
          filters:
            branches:
              only: master
