version: 2
jobs:
  install:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install

  deploy:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: git branch
      - run: ls -a

workflows:
  version: 2

  build_and_run_master:
    jobs:
      - install
      - deploy:
          requires:
            - install
          filters:
            branches:
              only: master
