defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:7.10

version: 2

jobs:
  install_deps:
    <<: *defaults
    steps:
      - checkout
      - run: yarn install
      - persist_to_workspace:
          root: .
          paths:
            - .

  build:
    <<: *defaults
    steps:
      - run: ls -la
      - attach_workspace:
          at: ~/repo/
      - run: ls -la
      - run: yarn run build
      - run: ls -la
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy_master:
    <<: *defaults
    steps:
      - run: ls -la
      - attach_workspace:
          at: ~/repo/build
      - run: ls -la
      - run: aws s3 sync build s3://react-deploy-test/ --region eu-central-1 --delete


workflows:
  version: 2
  build_and_deploy_master:
    jobs:
      - install_deps
      - build:
          requires:
            - install_deps
          filters:
            branches:
              only:
                - master
                - develop
      - deploy_master:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy_develop:
          requires:
            - build
          filters:
            branches:
              only: develop
