version: 2
jobs:
  defaults: &defaults
    docker:
      - image: circleci/node:7.10
    working_directory: /tmp
    steps:
      - checkout

  build:
    <<: *defaults
    steps:
      - checkout
      - run: yarn run install
      - run: yarn run build
      - persist_to_workspace:
        - root: build

  deploy_master:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/build
      # change to deployment command later
      - run: ls -a

workflows:
  version: 2

  build_and_deploy_master:
    jobs:
      - install
      - build:
          requires:
            - install
      - deploy_master:
          requires:
            - build
          filters:
            branches:
              only: master
