defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:7.10

version: 2

jobs:
  install_deps:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Package Cache
          keys:
            - npm-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - npm-v1-{{ .Branch }}
            - npm-v1-master
            - npm-v1-
      - run: npm install
      - save_cache:
          name: Save Package Cache
          key: npm-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: .
          paths:
            - .

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo/
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy_master:
    docker:
      - image: wilson208/circleci-awscli
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      # deploying to:
      # http://react-deploy-test.s3-website.eu-central-1.amazonaws.com/
      - run: aws s3 sync build s3://react-deploy-test/ --region eu-central-1 --delete


workflows:
  version: 2
  build_and_deploy_master:
    jobs:
      - install_deps
      - build:
          requires:
            - install_deps
          filters:
            branches:
              only:
                - master
                - develop
      - deploy_master:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy_develop:
          requires:
            - build
          filters:
            branches:
              only: develop
